backend:
  name: git-gateway
collections:
  - name: "blog"
    label: "Blog"
    folder: 'posts'
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Date", name: "date", widget: "datetime"}
media_library:
  name: cloudinary
  config:
    cloud_name: markg16
    api_key: 219387516764329
    default_transformations:
      - fetch_format: auto
        quality: auto
        width: 400
        crop: scale
